### ISSUE TITLE
Live chat embed does not work

### ISSUE THREAD

**Issue by TUSAB-web** [nystudio107/craft-youtubeliveembed#12]
### Describe the bug
When calling the live chat embed, it does not render, and the network tab indicates a 200 error trying to get the live chat. In Firefox, it gives a more helpful error (see below) but in Safari it’s just blank space on the page.

### To reproduce
Steps to reproduce the behaviour:
1. Put the live chat embed in your code: {{ craft.youtubelive.embedChat() }}
2. Set the stream to live in the settings
3. Load the page, and the embedded Chat will not render.

### Expected behaviour
The live chat should render.

### Screenshots
<img width="709" alt="embedchaterror" src="https://user-images.githubusercontent.com/52001038/106321681-a2957700-6242-11eb-9041-6e2c8deb0ef9.png">

### Versions
- Plugin version: 1.0.8
- Craft version: Pro 3.6.1

**Comment by TUSAB-web** [comment]
I found this tidbit on the interwebs....

https://www.embedplus.com/embed-youtube-live-chat-box-with-live-stream-embed-wordpress.aspx

"Note: Google has decided to end support for embedded live chat as of January 2021."

**Comment by ryanirelan** [comment]
@TUSAB-web Thank you for reporting this. I've been playing a cat and mouse game with YouTube for a while, as they routinely break things. Let me see what I can do for a workaround!

**Comment by ryanirelan** [comment]
@TUSAB-web This is still working for me on the site. When you inspect the page in your browser, is the site URL populated in the `embed_domain` URL param? Here's the code that generates the embed: https://github.com/nystudio107/craft-youtubeliveembed/blob/v1/src/templates/embeds/youtube-live-chat.twig#L31

**Comment by frutality** [comment]
@ryanirelan they rolled it back. I can confirm it wasn't working for a few days.

**Comment by TUSAB-web** [comment]
I checked to make sure the embed_domain was working. I think it was just broken by YouTube for a few days. I just tried it again and it pulls up the chat window.
